apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: blue-green-appset
spec:
  generators:
  - list:
      elements:
        - cluster: in-cluster
          url: https://kubernetes.default.svc
          env: hub
        - cluster: external-cluster
          url: https://api.cluster-gnwjg.gnwjg.sandbox772.opentlc.com:6443
          env: external
  template:
    metadata:
      name: '{{cluster}}-blue-green'
    spec:
      project: default
      source:
        repoURL: https://github.com/cawright-rh/argocd-example-apps.git
        targetRevision: HEAD
        path: blue-green
      destination:
        server: '{{url}}'
        namespace: blue-green
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
