apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: standalone-app
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: standalone-app
    server: https://api.cluster-gnwjg.gnwjg.sandbox772.opentlc.com:6443
  project: default
  source:
    path: helm-dependency
    repoURL: https://github.com/cawright-rh/argocd-example-apps.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
